spring:
  application:
    name: eureka
security:                     #为eureka——server 添加认证
  basic:
    enabled: true
  user:
    name: admin
    password: 123456
---             #---以上的是公用配置   一下的 可以通过 spring.profiles  选择以哪个配置文件运行 
spring:
  profiles: eureka1
server:
  port: 8761
eureka:                                                         # 不作为client使用 (单机模式)   register-with-eureka: false   fetch-registry: false
    instance:
      hostname: eureka1
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.ipAddress}:${server.port} 
    client:
      service-url:
        defaultZone: http://admin:123456@eureka2:8762/eureka/
        instance:
---        
spring:
  profiles: eureka2
server:
  port: 8762
eureka:
    instance:
      hostname: eureka2
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    client:
      service-url:
        defaultZone: http://admin:123456@eureka1:8761/eureka/