server:
  #address: 127.0.0.1              访问的ip
  #context-path: /SpringBootProject/     #项目名
  port: 8081                     #端口
  session.timeout: 30            #session过期时间      
  tomcat.uri-encoding: UTF-8     #tomcat编码格式
  #error.path:                  访问的地址如果找不到返回一个特定的页面
spring:  
  thymeleaf:                       
    cache: false                                         #页面缓存
    prefix: classpath:/page                              #访问页面加前缀
    suffix: .html                                        #访问页面加后缀
    encoding: UTF-8                                      #页面编码格式
  application:
    name: spring-boot-project                                #建议全部小写     并且不能使用 下划线_ (否则eureka不能通过application.name 获取ip port)
eureka:
  client:
    service-url:                                             # eureka 要实现健康检查需要导入  spring-boot-starter-actuator 包
      defaultZone: http://admin:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}   
spring-boot-user:  #ribbon 配置
  ribbon:
    NFLoadBlancerRuleClassName: com.netflix.loadbalancer.RandomRule     
      
  

    
 